/**
 * Curated hotspot seed data per market. Sourced from local
 * editorial knowledge — replaceable from Supabase / Google Places
 * once the live integration is wired.
 *
 * Image URLs use Unsplash photo IDs known to be stable. Replace
 * with Google Place Photos when GOOGLE_PLACES_API_KEY is present.
 */

const u = (id, w = 1200) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=70`;

export const HOTSPOTS = {
  'palm-springs': [
    {
      id: 'workshop-kitchen',
      name: 'Workshop Kitchen + Bar',
      category: 'restaurant',
      neighborhood: 'Downtown',
      priceLevel: 3,
      rating: 4.6,
      minutesDrive: 7,
      description:
        "James Beard-nominated New American — open kitchen, raw bar, and the desert's most precise cocktail program. Reserve 2 weeks out for the patio.",
      tags: ['Date night', 'Patio', 'Cocktails'],
      hours: '5–10 PM, closed Mon',
      website: 'https://workshoppalmsprings.com',
      image: u('1517248135467-4c7edcad34c4'),
      featured: true,
    },
    {
      id: 'tac-quila',
      name: 'Tac/Quila',
      category: 'restaurant',
      neighborhood: 'Downtown',
      priceLevel: 2,
      rating: 4.5,
      minutesDrive: 7,
      description:
        'Modern Oaxacan plates and a 200-bottle agave list inside a converted bungalow. The mole flight is the move.',
      tags: ['Late night', 'Agave bar'],
      hours: '11:30 AM–11 PM',
      website: 'https://www.tacquila.com',
      image: u('1565299624946-b28f40a0ae38'),
    },
    {
      id: 'mr-lyons',
      name: "Mr. Lyons Steakhouse",
      category: 'restaurant',
      neighborhood: 'Downtown',
      priceLevel: 4,
      rating: 4.6,
      minutesDrive: 6,
      description:
        'A red-leather, low-light Old Hollywood steakhouse — the dry-aged ribeye and a Sazerac is the Palm Springs date.',
      tags: ['Old Hollywood', 'Steak'],
      hours: '5:30–10 PM',
      website: 'https://mrlyonsps.com',
      image: null, // gradient fallback — replace with Google Place Photo when key is set
    },
    {
      id: 'tahquitz-canyon',
      name: 'Tahquitz Canyon',
      category: 'hike',
      neighborhood: 'Indian Canyons',
      priceLevel: 1,
      rating: 4.8,
      minutesDrive: 6,
      description:
        '1.8 mi loop on tribal land — palm oasis, year-round 60-ft waterfall, and the cleanest air in the valley. Best at 8 AM.',
      tags: ['Easy', 'Waterfall', '1–2 hr'],
      hours: '7:30 AM–5 PM',
      website: 'https://www.tahquitzcanyon.com',
      image: u('1469854523086-cc02fe5d8800'),
      featured: true,
    },
    {
      id: 'aerial-tram',
      name: 'Palm Springs Aerial Tramway',
      category: 'experience',
      neighborhood: 'Chino Canyon',
      priceLevel: 2,
      rating: 4.7,
      minutesDrive: 9,
      description:
        "World's largest rotating tram — 2.5 mi in 10 minutes from desert floor to 8,500-ft pine forest. Sunset rides book out 2+ weeks early.",
      tags: ['Sunset', 'Bucket list'],
      hours: '10 AM–9:45 PM',
      website: 'https://pstramway.com',
      image: u('1506905925346-21bda4d32df4'),
      featured: true,
    },
    {
      id: 'parker-palm-springs',
      name: 'Parker Palm Springs',
      category: 'experience',
      neighborhood: 'Sunrise Park',
      priceLevel: 4,
      rating: 4.5,
      minutesDrive: 12,
      description:
        'Jonathan Adler–designed grounds, a Norma cocktail bar, and Mr. Parker\'s for dinner. Day-pass available — book the spa first.',
      tags: ['Spa', 'Iconic design'],
      hours: '24 hours',
      website: 'https://www.parkerpalmsprings.com',
      image: u('1582719478250-c89cae4dc85b'),
    },
    {
      id: 'truss-twine',
      name: 'Truss & Twine',
      category: 'cocktail-bar',
      neighborhood: 'Downtown',
      priceLevel: 3,
      rating: 4.7,
      minutesDrive: 7,
      description:
        'Classic + pre-Prohibition cocktails done with obsessive precision. Sister-bar to Workshop. Bartender\'s choice never disappoints.',
      tags: ['Cocktails', 'Pre-Prohibition'],
      hours: '5 PM–close',
      website: 'https://trussandtwineps.com',
      image: u('1514362545857-3bc16c4c7d1b'),
    },
    {
      id: 'kings-highway',
      name: "King's Highway Diner",
      category: 'cafe',
      neighborhood: 'Sunrise Park',
      priceLevel: 2,
      rating: 4.4,
      minutesDrive: 12,
      description:
        'The Ace Hotel coffee shop — best breakfast burrito in the valley, midcentury booths, served by the pool deck.',
      tags: ['Breakfast', 'Pool view'],
      hours: '7 AM–9 PM',
      website: 'https://acehotel.com/palm-springs/kings-highway',
      image: u('1567620905732-2d1ec7ab7445'),
    },
    {
      id: 'modernism-architecture-tour',
      name: 'PS Architecture Tours',
      category: 'tour',
      neighborhood: 'Multiple',
      priceLevel: 2,
      rating: 4.8,
      minutesDrive: 0,
      description:
        '3-hour van tour through 30+ Neutra, Lautner, Wexler & Frey homes — the best primer on Palm Springs midcentury, period.',
      tags: ['MCM', 'Architecture'],
      hours: 'By appointment',
      website: 'https://psarchitecturetours.com',
      image: u('1600596542815-ffad4c1539a9'),
    },
    {
      id: 'two-bunch-palms',
      name: 'Two Bunch Palms (DHS)',
      category: 'spa',
      neighborhood: 'Desert Hot Springs',
      priceLevel: 4,
      rating: 4.6,
      minutesDrive: 22,
      description:
        'Adults-only mineral hot springs sanctuary — the original Hollywood escape. Day pass + grotto soak is the move.',
      tags: ['Adults only', 'Wellness'],
      hours: '8 AM–10 PM',
      website: 'https://twobunchpalms.com',
      image: u('1540555700478-4be289fbecef'),
    },
  ],
  'san-miguel-de-allende': [
    {
      id: 'casa-dragones',
      name: 'Casa Dragones Tasting Room',
      category: 'experience',
      neighborhood: 'Centro',
      priceLevel: 4,
      rating: 4.9,
      minutesDrive: 3,
      description:
        'A guided tasting in the original Casa Dragones courtyard — the world\'s most elegant tequila experience. Reserve 30+ days out.',
      tags: ['Tequila', 'Reservation'],
      hours: 'By appointment',
      website: 'https://www.casadragones.com',
      image: u('1514362546005-9b48f7bb95a6'),
      featured: true,
    },
    {
      id: 'parroquia-jardin',
      name: 'La Parroquia & El Jardín',
      category: 'experience',
      neighborhood: 'Centro',
      priceLevel: 1,
      rating: 5.0,
      minutesDrive: 2,
      description:
        'The pink-stone neo-Gothic cathedral facing the central garden. Show up at 7:30 AM for the bells, or 7 PM for the golden-hour glow.',
      tags: ['Iconic', 'Photo'],
      hours: 'Always',
      website: null,
      image: u('1518105779142-d975f22f1b0a'),
      featured: true,
    },
    {
      id: 'la-azotea',
      name: 'La Azotea',
      category: 'cocktail-bar',
      neighborhood: 'Centro',
      priceLevel: 3,
      rating: 4.7,
      minutesDrive: 2,
      description:
        'Rooftop with the single best Parroquia view in town — go at 7 PM, order the mezcal flight, stay through the bell-tower hour.',
      tags: ['Rooftop', 'Sunset'],
      hours: '5 PM–1 AM',
      website: 'https://www.laazoteasanmiguel.com',
      image: null,
    },
    {
      id: 'aperi',
      name: 'Áperi',
      category: 'restaurant',
      neighborhood: 'Centro',
      priceLevel: 4,
      rating: 4.8,
      minutesDrive: 3,
      description:
        "Chef Olivier Deboise's seasonal tasting menu inside Hotel Dôce 18 — the most considered cooking in SMA, sourced from local farms.",
      tags: ['Tasting menu', 'Date night'],
      hours: '6:30–11 PM, closed Mon',
      website: 'https://aperi.mx',
      image: null,
      featured: true,
    },
    {
      id: 'lavanda',
      name: 'Lavanda Café',
      category: 'cafe',
      neighborhood: 'Centro',
      priceLevel: 2,
      rating: 4.7,
      minutesDrive: 3,
      description:
        'Garden café for slow breakfasts — chilaquiles, chocolate caliente, and the prettiest courtyard in Centro.',
      tags: ['Breakfast', 'Courtyard'],
      hours: '8 AM–4 PM',
      website: null,
      image: u('1509042239860-f550ce710b93'),
    },
    {
      id: 'fabrica-aurora',
      name: 'Fábrica La Aurora',
      category: 'gallery',
      neighborhood: 'San Antonio',
      priceLevel: 1,
      rating: 4.7,
      minutesDrive: 6,
      description:
        'A converted 1902 textile factory holding 40+ galleries, design shops, and the city\'s best contemporary art. Free to wander.',
      tags: ['Art', 'Free'],
      hours: '10 AM–7 PM',
      website: 'https://fabricalaaurora.com',
      image: u('1513475382585-d06e58bcb0e0'),
    },
    {
      id: 'instituto-allende',
      name: 'Instituto Allende',
      category: 'experience',
      neighborhood: 'Centro Sur',
      priceLevel: 1,
      rating: 4.6,
      minutesDrive: 4,
      description:
        '1736 cantera-stone arts campus — frescoes, courtyards, and the rooftop view that put SMA on the cover of Condé Nast.',
      tags: ['Architecture', 'Free'],
      hours: '9 AM–6 PM',
      website: null,
      image: u('1523730205978-59fd1b2965e3'),
    },
    {
      id: 'mercado-tuesday',
      name: 'Tianguis (Tuesday Market)',
      category: 'experience',
      neighborhood: 'San Juan de Dios',
      priceLevel: 1,
      rating: 4.5,
      minutesDrive: 8,
      description:
        'The largest open-air market in the region — produce, leather, ceramics, and tianguis food stalls. Tuesdays only, arrive by 10 AM.',
      tags: ['Tuesday only', 'Local'],
      hours: 'Tue 7 AM–4 PM',
      website: null,
      image: u('1488459716781-31db52582fe9'),
    },
    {
      id: 'mama-mia',
      name: 'Mama Mia',
      category: 'nightlife',
      neighborhood: 'Centro',
      priceLevel: 2,
      rating: 4.5,
      minutesDrive: 2,
      description:
        'SMA institution — courtyard dinner downstairs, live mariachi or jazz on the rooftop after 10. The locals\' late-night.',
      tags: ['Live music', 'Rooftop'],
      hours: '8 AM–2 AM',
      website: 'https://mamamiasma.com',
      image: u('1514525253161-7a46d19cd819'),
    },
    {
      id: 'sma-thermal',
      name: 'La Gruta Thermal Springs',
      category: 'spa',
      neighborhood: 'Highway 51',
      priceLevel: 2,
      rating: 4.6,
      minutesDrive: 18,
      description:
        'Three connected thermal pools — the third is reached through a tunnel into a candlelit cave. Go early, before 10 AM.',
      tags: ['Thermal', 'Cave'],
      hours: '8 AM–5 PM',
      website: 'https://lagrutaspa.com',
      image: null, // de-duplicated from Two Bunch Palms; gradient fallback
    },
  ],
};

export const CATEGORIES = [
  { id: 'restaurant', label: 'Restaurants' },
  { id: 'cocktail-bar', label: 'Bars' },
  { id: 'cafe', label: 'Cafés' },
  { id: 'experience', label: 'Experiences' },
  { id: 'hike', label: 'Outdoors' },
  { id: 'gallery', label: 'Galleries' },
  { id: 'spa', label: 'Spa & wellness' },
  { id: 'tour', label: 'Tours' },
  { id: 'nightlife', label: 'Nightlife' },
];
